### PR TITLE
Fix for PHPStorm exception handling check

### PR DESCRIPTION
**Pull request by gerritdrost**
Fixes https://github.com/auraphp/Aura.Sql/issues/165

### CODE REVIEW

**Comment by gerritdrost** [comment]
The travis build fail is not related to the code, but to an error in the travis setup. Extract from the build log:
```
[...]
PHP 5.3 is supported only on Precise.
See https://docs.travis-ci.com/user/reference/trusty#PHP-images on how to test PHP 5.3 on Precise.
Terminating.
```

**Comment by pmjones** [comment]
Thanks!

**Comment by sudo-plz** [comment]
Hi, is it possible to get a new version tag for this fix? When working on a project it throws many warnings in PHPStorm and this may cause actual warning messages to be overlooked.

**Comment by harikt** [comment]
Hi @RoyboyNL ,

Released https://github.com/auraphp/Aura.Sql/tree/2.5.2  .

Hope that helps! .

**Comment by sudo-plz** [comment]
Thanks @harikt!

**Pull request merged**
