### PR TITLE
Fix for issue #96. Allow first bind value of query with numbered placeholders to be null

### PR DESCRIPTION
**Pull request by frederikbosch**
Fixes issue #96 provided with a test.

### CODE REVIEW

**Comment by mlaphp** [comment]
Good. I say we get rid of the isset() entirely and go only with array_key_exists().

**Comment by pmjones** [comment]
(Who the hell is mlaphp? ;-)

I say get rid of the isset() entirely and use only array_key_exists().

**Comment by frederikbosch** [comment]
@pmjones No problem to get rid of isset.

**Comment by pmjones** [comment]
Good deal! I'll let the CI stuff run and then merge. Thanks!

**Comment by frederikbosch** [comment]
@pmjones No problem, thank you for the wonderful Aura libraries!

ps. I would be happy with a new version, could you tag one? :)

**Comment by pmjones** [comment]
2.4.1 is released :-)

**Pull request merged**
