### PR TITLE
added yield*() functions parallel to fetch*() functions. removed callables

### PR DESCRIPTION
**Pull request by pavarnos**
towards #110.
The diff looks a little weird in places: i added the new yield() functions directly below the fetch() functions, but removing the callable parameter in the original fetch()es seems to screw up the diff.
Did not do yieldGroup() because thought that it may not make sense as rows may be processed out of order?
Used modern array notation [] instead of array(). Happy to go back and fix that if needed.

### CODE REVIEW

**Comment by pmjones** [comment]
Thanks for this!

> The diff looks a little weird in places

Tell you what -- for purposes of reviewing the diff, can you put all the new `yield*()` in a block at the end? We can rearrange the methods later.

**Comment by pavarnos** [comment]
aagh. please excuse this noob getting confused with git. made a new pull request. whats the best way to clean up this mess?

**Comment by pmjones** [comment]
Heh, no problem. Looking over it now. The beatings will commence only if absolutely necessary. ;-)

**Comment by pmjones** [comment]
OK, we're moving along nicely! Some style issues remain. If you could:

- Change `[ ]` to `[]` in the "empty array declarations (no space between the brackets).

- I don't think we need to wrap the `while()` conditions in double parens; a single set of parens should do. I.e., change from `while (($row = $sth->fetch(self::FETCH_NUM)))` to `while ($row = $sth->fetch(self::FETCH_NUM))`.

- Finally, if you could change uses of `array $values = array()` (and all similar) to `array $values = []`, that would be nice. I think they were like that before, so it's not your fault.

You should be able to make these changes in your existing branch; once you push them, this PR will auto-update itself.

How's that sound?

**Comment by pavarnos** [comment]
this is the most fun i've had programming for a long time...

**Pull request closed without merging**
