### PR TITLE
Add insert multiple rows with prepared statements emulation

### PR DESCRIPTION
**Pull request by sasha-x**
Here is my solution for https://github.com/auraphp/Aura.Sql/issues/22
Using pattern: 
INSERT INTO tbl_name (a,b,c) VALUES (?,?,?), ...
and "Rebuilder" way.
All comments and negative sql examples are welcome.
Or may be reopen issue and discuss it there?

### CODE REVIEW

**Comment by sasha-x** [comment]
I am sorry. Previous commit was broken.

**Comment by pmjones** [comment]
I think this would be more appropriate in the Aura.SqlQuery package, so that a multi-insert can be put together programmatically and tested well. Cf. https://github.com/auraphp/Aura.SqlQuery/issues/16

**Comment by sasha-x** [comment]
It's up to you.

**Comment by pmjones** [comment]
Yeah, it'd be better as part of the Query system.

**Pull request closed without merging**
