### PR TITLE
query objects "where" method improvement

### PR DESCRIPTION
**Pull request by MAXakaWIZARD**
Change implicit "value" param to explicit in "where" method of WhereTrait, so it is visible to client code

### CODE REVIEW

**Comment by pmjones** [comment]
This is actually a variation on something we did earlier, and then moved away from. The problem was that eventually a user will intend to pass "false" as a value to bind (sometimes it gets converted to an integer zero, sometimes to an SQL boolean representation).

**Comment by MAXakaWIZARD** [comment]
Well, now we have "magic" param in this method now, I discovered it suddenly, when was looking in library's source code.

**Comment by pmjones** [comment]
Yeah, it's a tough one. In a later variation we had an explicit param defaulting to a magic constant value (an MD5 hash of some string like "ThisValueIsReallyNotHere").  Instead of func_get_args() we checked against that magic constant value. That was weird too.

Maybe this is more a documentation issue?

**Comment by MAXakaWIZARD** [comment]
What if we put there some object as default value?

**Comment by pmjones** [comment]
Although a "null object" would be perfect here, PHP won't let you do `function ($foo = new Foo)`.

**Comment by MAXakaWIZARD** [comment]
I think we have only two solutions:
1) Mention it in docs.
2) Create separate method with name "whereVal" or something like this and mention it in docs.

**Comment by pmjones** [comment]
Of the two solutions, I like the first one better. If you feel like adding some notes on where() and having() methods, that would be really cool; if not, I will. Regardless, thanks for your attention to the details here.

**Comment by pmjones** [comment]
(I'll close this PR when we have docs in place.)

**Comment by harikt** [comment]
Closed via #51

**Pull request closed without merging**
