### PR TITLE
Update GitHub Actions for 5.x

### LINKED ISSUE #195: Scrutinizer Error
> Waiting for External Code Coverage 
> 
> The code coverage data was not received within the specified time. Please make sure your third-party service is configured to send code coverage data.
>
> Code coverage data is not yet available.
> Code Coverage was not sent to Scrutinizer.
> Make sure that you have set-up your external service correctly.
> You can find more information on this in the documentation:
>
> https://scrutinizer-ci.com/docs/tools/external-code-coverage/
> 
> If you need help you can also email support@scrutinizer-ci.com.
> 
> https://scrutinizer-ci.com/g/auraphp/Aura.Sql/inspections/6611606a-1e89-4608-a139-3e46f11cee50

### PR DESCRIPTION
**Pull request by kenjis**
#197 for 5.x.
Closes #195

### CODE REVIEW

**Comment by kenjis** [comment]
https://scrutinizer-ci.com/g/auraphp/Aura.Sql/inspections/1bbcbf63-9759-431c-ab01-81bf5fc86260
```
composer install --no-interaction --no-scripts
inferred 00:02
The command exited with code 2.

Loading composer repositories with package information
Warning from https://repo.packagist.org: Support for Composer 1 is deprecated and some packages will not be available. You should upgrade to Composer 2. See https://blog.packagist.com/deprecating-composer-1-support/
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - This package requires php >=8.1 but your PHP version (7.3.15) does not satisfy that requirement.
```

**Comment by kenjis** [comment]
@koriym Do you know why scrutinizer uses PHP runtime 7.3.15?

**Comment by koriym** [comment]
Because it's cached. Besides, They don't provide an image of PHP 8.1, so you'll have to ignore it or install it to solve the problem.

**Comment by brandonsavage** [comment]
Does this project really need the bloat of Scrutinizer when we could simply run Psalm or Stan on this?

**Comment by koriym** [comment]
@brandonsavage The scrutinizer gives you a score for the complexity of the method, which phpstan/psalm doesn't have. It's a feature I like.

But if it's too much of a hassle to maintain, I guess we can remove it.

**Comment by kenjis** [comment]
> so you'll have to ignore it or install it to solve the problem.

Will ignoring and waiting solve the problem?
I don't know how to install PHP 8.1.

**Comment by kenjis** [comment]
If we don't merge this PR, the GitHub Actions will fail all the time, so I'll merge it anyway.

**Pull request merged**
