### PR TITLE
Sqlite-specific query objects

### PR DESCRIPTION
**Pull request by MAXakaWIZARD**
Also get rid of some duplication via creating LimitTrait, OffsetTrait and OrderByTrait

### CODE REVIEW

**Comment by MAXakaWIZARD** [comment]
Link to SQLite SQL syntax documentation: http://www.sqlite.org/lang.html

**Comment by harikt** [comment]
Nice and Thank you. It seems good to me.

**Comment by harikt** [comment]
and we are about to release the package. @pmjones What do you feel on this?

**Comment by harikt** [comment]
Just a different note @MAXakaWIZARD . Your site looks nice . Also do remember to checkout to new branch and commit, else you will get into trouble :-1:  .

**Comment by MAXakaWIZARD** [comment]
Thanks! What do you mean "checkout to new branch and commit, else you will get into trouble". I regularly do pull upstream.

**Comment by MAXakaWIZARD** [comment]
About release. I think we should wait until I implement PgSql query objects...

**Comment by harikt** [comment]
@MAXakaWIZARD what I meant is when you commit to develop of your branch, and at some point the commit is not accepted, you may get into merge conflicts or the commits will be already there when you send a new PR. 

That is to get rid of these we make a new branch from develop and later send a PR on that merging with upstream.

I wrote something how I worked, may be there can be a better approach though, you can read at  http://auraphp.com/blog/2012/07/13/contributing-to-aura-project/

Thank you for the contributions.

**Comment by harikt** [comment]
Do checkout subpackages of v2 (  https://github.com/auraphp/Aura.Sql/tree/subpackages ) . So we can have it in early stages itself.

Thanks

**Comment by MAXakaWIZARD** [comment]
Ok, I see. Thanks for good points!

**Comment by pmjones** [comment]
Sweet!

**Pull request merged**
