### PR TITLE
Sorry the earlier PR didn't worked :( . Trying the other from the docs h...

### PR DESCRIPTION
**Pull request by harikt**
...ttp://about.travis-ci.org/docs/user/database-setup/

@pmjones sorry the earlier commit didn't worked as expected.  I have looked into the docs once again and made the changes. I hope this time it should work.

### CODE REVIEW

**Comment by pmjones** [comment]
No worries -- applying now.

**Comment by harikt** [comment]
This time it worked, but errors are different. I guess its due to the `tests/globals-dist.php` . Will check it.

**Comment by harikt** [comment]
ok so the problem is with the globals-dist.php . Do you have any thoughts how we can make one for travis ? I wonder whether its a good idea to keep globals.php for travis ?

**Comment by pmjones** [comment]
What _should_ the globals-dist.php values be? I'm happy if they change to match what Travis needs.

**Comment by harikt** [comment]
If I am correct I am giving another PR #29 looking into the information from http://about.travis-ci.org/docs/user/database-setup/ 

Consider looking whether its correct :) .

**Comment by harikt** [comment]
It fails :( . Wondering why the database not creating . I want to ask in travis support .

**Pull request merged**
