### PR TITLE
Added a whereIn and a orWhereIn method to the where traits

### PR DESCRIPTION
**Pull request by geissler**

### CODE REVIEW

**Comment by pmjones** [comment]
I think this functionality is already supported.  You can do, for example ...

```
// $foo_list is an array of values
$select->where('foo IN (?)', $foo_list);
```

... or ...

```
// $foo_list is an array of values
$select->where('foo IN (:foo_list)');
$select->addBind(['foo_list' => $foo_list]);
```

... and the list arrays will be exploded, quoted, and comma-separated for you.  (This is something that happens at the DB adapter level.)

Is that existing functionality sufficient for your purposes?

**Comment by pmjones** [comment]
@geissler Given my comment about existing functionality, is this still a problem?

**Comment by geissler** [comment]
Sorry, i totally have forgotten that. The existing functionality is sufficient.

**Comment by harikt** [comment]
@geissler cool. I am closing this @pmjones  :) .

**Pull request closed without merging**
