### PR TITLE
Query\Mysql\Select with SQL_CALC_FOUND_ROWS and other mysql-specific flags

### PR DESCRIPTION
**Pull request by MAXakaWIZARD**
Query\Mysql\Select with such options
HIGH_PRIORITY
STRAIGHT_JOIN
SQL_CALC_FOUND_ROWS
SQL_CACHE
SQL_NO_CACHE
SQL_SMALL_RESULT
SQL_BIG_RESULT
SQL_BUFFER_RESULT

### CODE REVIEW

**Comment by pmjones** [comment]
Wow dude.  I may merge this manually instead of automatically, because I'd like to touch up some stylistic stuff, but aside from that it looks impressive.  Please please please tell me you can do something like this, or know someone who can, for Postgres and Sqlite.

**Comment by pmjones** [comment]
Say, where do the names for the constants come from?

**Comment by MAXakaWIZARD** [comment]
Well, I think i can do that for Postgres abd Sqlite, but I wanted to do INSERT IGNORE for mysql first

**Comment by MAXakaWIZARD** [comment]
Names for the constants come from Query\Mysql\Select class (FLAG_STRAIGHT_JOIN and so on), if I properly understood, what you mean.

**Comment by pmjones** [comment]
Absolutely; get Mysql completed, and if you can proceed to the others thereafter, that would be fantastic.

**Comment by pmjones** [comment]
Oh, on the constants, what I meant was, are those names that MySQL uses someplace, or did you make them up yourself, or what?

**Comment by MAXakaWIZARD** [comment]
Hmm.. Here's the link to mysql select manual page: http://dev.mysql.com/doc/refman/5.5/en/select.html

**Comment by pmjones** [comment]
Exactly what I was hoping for; the constant names match the MySQL clauses. You may proceed, sir, and thank you!

**Comment by MAXakaWIZARD** [comment]
Thank you too!

**Comment by MAXakaWIZARD** [comment]
Damn.. Why all those commits were added to this PR?

**Comment by pmjones** [comment]
/me shrugs

If you like, close the request and open a new (cleaner) one.

**Comment by MAXakaWIZARD** [comment]
hmm, maybe we can merge this big PR, cause it covers almost all mysql features

**Comment by MAXakaWIZARD** [comment]
Or I can split it into 4 separate PRs, if it's possible

**Comment by pmjones** [comment]
I'm good with a single big one for MySQL. I can edit and rearrange here as needed. Let me know when you feel it's complete.

**Comment by pmjones** [comment]
Oh, and if there's some way to avoid the whitespace changes coming through (e.g. in docblocks) that would be really helpful in finding the substantive differences.

**Comment by MAXakaWIZARD** [comment]
Well, problem is not with whitespaces, but with caret returns. I tried to fix that, but no luck.

**Comment by pmjones** [comment]
No problem. It's a convenience, not a deal-breaker.

**Comment by pmjones** [comment]
@MAXakaWIZARD Are you ready for me to do the merge?

**Comment by MAXakaWIZARD** [comment]
Yep

**Comment by MAXakaWIZARD** [comment]
What is the proper way to merge you changes back?
git remote add upstream git@github.com:auraphp/Aura.Sql.git
git fetch upstream
git rebase upstream/develop
Is that right?

**Comment by pmjones** [comment]
Great question. That looks about right but I am not a Git guru. :-/

**Comment by MAXakaWIZARD** [comment]
Ok, I already merged back. Will try to deliver Sqlite and Postgres queries soon.

**Comment by pmjones** [comment]
You are a good man, sir, and I appreciate it a great deal.

**Pull request merged**
