### PR TITLE
Correctly handle zero-indexed placeholder arrays on execute

### LINKED ISSUE #75: Sequential params on execution queries should be 0-indexed
Currently, fetch*(), perform(), etc. assume a 1-indexed array when dealing with non-named (question-mark) params. The base PDO execute() uses a 0-indexed array. This results in inconsistent behavior between ExtendedPDO and PDO, forcing workarounds like

https://gist.github.com/iansltx/6d0181c835e5afbf2965#file-gistfile1-php-L6

(I feed those results into fetchOne() or fetchAll() depending on whether I'm counting or retrieving results).

It sounds like the inconsistency here is because http://www.php.net//manual/en/pdostatement.bindvalue.php uses a 1-indexed array and http://www.php.net/manual/en/pdostatement.execute.php uses a 0-indexed array, when interacting with non-named params. php.net docs need an edit to clarify that this is what's going on on the execute site, but the editor isn't playing nice with me right now.

Fixing this issue will be backwards incompatible with the hack posted above, though for folks who've used 1-indexed as input instead and have a properly sized array it'd be possible to keep their implementations working.

### PR DESCRIPTION
**Pull request by iansltx**
No test yet; opening the PR to get feedback/test-running. Fixes #75.

### CODE REVIEW

**Comment by iansltx** [comment]
Let me know if y'all want me to close this PR and re-open with just the second commit; the first one doesn't solve the problem.

**Comment by harikt** [comment]
@iansltx I am seeing test also. or am I missing something?

This looks good to me. Paul will verify and merge. Be patient :+1:  .

Thank you.

**Comment by iansltx** [comment]
When I made the PR originally I only had the first commit, which didn't include a test. The test is there now :grin:

**Comment by pmjones** [comment]
Thanks for the test. This was an unexpected behavior from PDO; glad to see you caught it.

**Pull request merged**
