### PR TITLE
Query\Mysql\Update object with LIMIT feature

### PR DESCRIPTION
**Pull request by MAXakaWIZARD**
Start to develop non-standard SQL features for different database engines.
Proposed structure is:
Aura\Sql\Query/Mysql/Update.php
Aura\Sql\Query/Mysql/Select.php
Aura\Sql\Query/PgSql/Select.php
...
Aura\Sql\Query\Select.php
Aura\Sql\Query\Update.php
Aura\Sql\Query\Delete.php
and so on.

### CODE REVIEW

**Comment by harikt** [comment]
Nice and Thank you @MAXakaWIZARD

**Comment by MAXakaWIZARD** [comment]
When should I expect this PR to be merged?

**Comment by harikt** [comment]
@MAXakaWIZARD , @pmjones will look and merge. Please be patient. Yes I know there is lots of anxiety for every one.

**Comment by pmjones** [comment]
Tentatively accepting this; I reserve the right to reorganize.  It's a good idea.  Thanks!

**Pull request merged**
