### PR TITLE
ExtendedPdo::rollBack() return nothing

### PR DESCRIPTION
**Pull request by koriym**
Fixed to return the result of roll back.

### CODE REVIEW

**Comment by harikt** [comment]
We will wait for @pmjones here.

**Comment by koriym** [comment]
yes !

**Comment by stanlemon** [comment]
This is a nice compatibility change for any code that tests whether or not a rollback completely successfully or not.

**Comment by pmjones** [comment]
You are correct @koriym it should return boolean. My bad. Cannot auto-merge it any more; if you want to rebase, I will apply the patch so you automatically get credit on Github. If you don't want to, I'll note in the change log that it's your fix.

**Comment by koriym** [comment]
No problem. Rebased.

**Comment by koriym** [comment]
thanks @stanlemon

**Comment by pmjones** [comment]
Thanks @koriym !

**Comment by koriym** [comment]
@pmjones My pleasure. :+1:

**Comment by harikt** [comment]
:+1:

**Pull request merged**
