### PR TITLE
Fixing trailing commas and a documentation bug

### PR DESCRIPTION
**Pull request by jklein**
Trailing commas aren't allowed when calling a constructor, as is the code causes a parse error.  Also fixing a variable name to match the example above.

### CODE REVIEW

**Comment by harikt** [comment]
Thank you @jklein for your first contribution :+1:  .

**Comment by harikt** [comment]
aah by the way are you using any of the aura packages at Etsy ?

**Comment by jklein** [comment]
Not at the moment, but we might start using them in some of our open source projects via composer.  I'm currently using Aura for some side projects, and it's great!

**Comment by harikt** [comment]
oh nice to hear @jklein and do join the google groups. There was some discussions lately on framework level stuffs.

**Comment by harikt** [comment]
Have updated the contributors list and now you are also here http://auraphp.com/contributors/ :+1:  .

**Comment by pmjones** [comment]
Thanks a ton @jklein !

**Pull request merged**
