### PR TITLE
Return specific query type from connection

### PR DESCRIPTION
**Pull request by MAXakaWIZARD**
e.g. Mysql connection will return Query\Mysql\Select instead of Query\Select and so on

### CODE REVIEW

**Comment by pmjones** [comment]
There's only one thing wrong with this, and that is: there should be a way to get the "generic" query type from the connection. I envision a case where someone writes an app using only "generic" queries so that it is portable across MySQL, PostgreSQL, SQLite, etc.

**Comment by MAXakaWIZARD** [comment]
What should I do? Create newGenericSelect method and so on?

**Comment by pmjones** [comment]
There's two ways I can think of. Each has pros and cons.
1. Create a "use generic" property that gets set on the connection, maybe by constructor, maybe by setter method. Each newSelect() etc method checks that property and returns either a generic or a specific query object.  The problem here is that multiple classes may be using the connection, and some may want generic, and some may want specific.
2. Add a param to each newSelect() etc method to specify "I want a generic" (or a specific). The problem here is, do we default to generic, or to specific?

Your thoughts?

**Comment by MAXakaWIZARD** [comment]
Maybe just add new method newGenericSelect along with newSelect?

**Comment by pmjones** [comment]
The old behavior was the generic behavior; if there's a new method, it should be "newMysqlSelect" (etc).

**Comment by MAXakaWIZARD** [comment]
Your're right

**Comment by MAXakaWIZARD** [comment]
I think we should parametrize newSelect method. With default behaviour left untouched.

**Comment by pmjones** [comment]
On consideration, I think I like the idea of adding the "newMysqlSelect()" (etc) methods. That makes it completely obvious what's going on, and there's no need to pass params every time you want something different.

**Comment by MAXakaWIZARD** [comment]
Should we wait for Hari's thoughts?

**Comment by pmjones** [comment]
@harikt should be awake in a little while; I have no problem hearing what he thinks here.

**Comment by harikt** [comment]
I don't have a good answer here. I will say @pmjones can take the decision :+1: .

**Comment by harikt** [comment]
looking at this I feel we are splitting the `newSelect` method to every where. And it seems not good to me for the current time.

May be we need to think how we can change in the factory `Aura\Sql\Query\Factory` ( For easy look up https://github.com/auraphp/Aura.Sql/blob/develop/src/Aura/Sql/Query/Factory.php#L37 )

**Comment by harikt** [comment]
As `Select`, `Update`, `Delete` everything is moved to it's own class may be factory can get which connection and add it ? I need to look at it though.

**Comment by pmjones** [comment]
With all that in mind, and in the interest of maintaining backwards compatibility, the new db-specific methods should be named `newMysqlSelect()` (etc). @MAXakaWIZARD let me know if you think there are real problems with that.

**Comment by MAXakaWIZARD** [comment]
Ok then. I will do necessary changes

**Comment by MAXakaWIZARD** [comment]
I'm done, please tell your opinion

**Comment by pmjones** [comment]
My opinion is "merge it!" ;-)

For future reference, in your tests, you can use $this->assertInstanceOf('Class_Name', $object) instead of the get_class() stuff. I'll make the necessary changes on this one.

**Comment by MAXakaWIZARD** [comment]
No-no. I did it via InstanceOf first. But it showed to me that it is not suitable for checking that object is instance of child class or something like that

**Comment by MAXakaWIZARD** [comment]
Here's the example: http://3v4l.org/iD9bh

**Comment by pmjones** [comment]
Ah so! Good call.

**Comment by MAXakaWIZARD** [comment]
``` php
//imagine error here - it returns Query\Mysql\Select instead of Query\Select
$query = $connection->newSelect();
$isGenericQuery = $query instanceof \Aura\Sql\Query\Select; //true
```

**Comment by pmjones** [comment]
Your point is understood, sir; no change will be made.

**Pull request merged**
