### PR TITLE
PgSQL Query objects

### PR DESCRIPTION
**Pull request by MAXakaWIZARD**
Some refactoring and brand new PgSQL Query objects

### CODE REVIEW

**Comment by pmjones** [comment]
Dude, you're a machine!

**Comment by MAXakaWIZARD** [comment]
Well, it's a honor for me to work with you guys.

**Comment by MAXakaWIZARD** [comment]
Planning to do the same for Microsoft SQL Server

**Comment by pmjones** [comment]
Niiiice. Do you have access to an MS SQL server for testing? I do not, and so the MS SQL portions of the package may not work properly (although they used to).

**Comment by MAXakaWIZARD** [comment]
I see. I think it's real to install MSSQL and run tests against it.

**Comment by pmjones** [comment]
I recall it being more trouble than that; there's a PDO mssql driver that you need.

**Comment by pmjones** [comment]
Maybe "pdo_sqlsrv" provided by Microsoft, and I think it's installable only on Windows.

**Comment by MAXakaWIZARD** [comment]
Well, I use Windows, I'll try to do so, when will have some spare time.

**Comment by pmjones** [comment]
Very good, sir.

**Comment by harikt** [comment]
:+1:  good work @MAXakaWIZARD and nice to see your commits coming.

**Pull request merged**
