### PR TITLE
Fix issue #163

### PR DESCRIPTION
**Pull request by sunkan**
Add getAttribute and setAttribute functions to make sure pdo is
connected before calling the functions

### CODE REVIEW

**Comment by harikt** [comment]
Something that troubles me is : If `getAttribute` is not working, I think the `__call` will not work for other methods of pdo. That is a serious problem which need to be looked into I guess.

**Comment by sunkan** [comment]
But the problem is that we extends PDO. 
And because of that `__call` will never be called for native pdo functions

**Comment by harikt** [comment]
oh oh I see what you mean. 

Then the `__call` looks like a function that will never be called.

Thank you.

**Comment by sunkan** [comment]
The only other function that isn't implemented from the base class is `getAvailableDrivers` and that's a static function.

So the only missing functions in `AbstractExtendedPdo` where `setAttribute` and `getAttribute`

**Comment by harikt** [comment]
@pmjones do you have any thoughts on this, else I will merge this.

**Pull request merged**
