### PR TITLE
add getPdo()

### PR DESCRIPTION
**Pull request by pavarnos**
ref #150

### CODE REVIEW

**Comment by pmjones** [comment]
A couple of things. First, ExtendedPdoInterface needs getPdo() on it. Second, getPdo() should always return a PDO instance; this means that DecoratedPdo can return it right away, but ExtendedPdo should connect() and then return.  Objections?

**Comment by pavarnos** [comment]
ExtendedPdoInterface has getPdo() https://github.com/auraphp/Aura.Sql/pull/151/commits/812dfcf0e8771cb8ec3f94ef4383e8b2e8c205ed#diff-17e6536dc8cca90d75cc1d251abf5aa5R249
I've not been able to discern any pattern by which methods are grouped, so I added it after isConnected() in the class and interface.

re ExtendedPdo: so what should happen if the user calls disconnect() then getPdo()? Should it automatically reconnect? eg https://github.com/auraphp/Aura.Sql/pull/151/commits/812dfcf0e8771cb8ec3f94ef4383e8b2e8c205ed#diff-bdbc1b37686ca0aeb8da02735119783eR735

**Comment by pmjones** [comment]
> ExtendedPdoInterface has getPdo()

My bad!

> I've not been able to discern any pattern by which methods are grouped

Alphabetical, IIRC.

> what should happen if the user calls disconnect() then getPdo()? Should it automatically reconnect?

I think that's the least astonishing thing to do.

**Comment by pavarnos** [comment]
its not clear (to me) what went wrong with hhvm. any tips?

**Comment by pmjones** [comment]
Not clear to me either. It seems to be recent, as of maybe 30 days ago, that HHVM started misbehaving.

**Comment by pmjones** [comment]
@pavarnos Found the HHVM issue; the ExtendedPdoTest::testCall() method was blowing up. Resolved in a later commit.

**Pull request merged**
